action_set_relative(1);
action_draw_sprite(sprite291, 0, 0, -1);
action_font(font1, 0);
action_draw_text("15000", 5, 16);
action_color(0);
action_font(font2, 0);
action_draw_text("날개잃은 천사모찌 3개를 합성하여", 5, 45);
action_draw_text("천사모찌로 업그래이드 시킵니다.", 5, 65);
action_draw_text("(단, 합성실패시 날개잃은박스들은 모두 소멸되며, 성공시", 5, 85);
action_draw_text("에도 사라지지만, 성공시 천사박스 획득이 가능합니다.", 5, 105);
action_set_relative(0);
